version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - talk-pick-network
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - t4y

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - prometheus
    networks:
      - t4y

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - t4y

  app:
    image: 536697254327.dkr.ecr.ap-northeast-2.amazonaws.com/talkpick-server:latest
    container_name: TalkPick_Server
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - talk-pick-network
    env_file:
      - .env
    restart: always  # 안정성을 위해 추가

networks:
  t4y:
    driver: bridge
  talk-pick-network:

volumes:
  grafana-data:
  prometheus-data: