jwt:
  secret: ${JWT_SECRET}
  accessTokenExpireTime: ${JWT_ACCESS_EXPIRE_TIME}

server:
  port: ${AUTH_PORT}
  tomcat:
    threads:
      max: ${THREADS_MAX}
    accept-count: ${ACCEPT_COUNT}

spring:
  config:
    import: optional:file:.env[.properties]